# Generated by Django 4.2.5 on 2023-10-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_task_description_task_label_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('shopping', 'Shopping')], default='personal', max_length=8),
        ),
    ]
